
@host = http://localhost:8000

###
GET {{host}}/users
Accept: application/json

###
GET {{host}}/users/1
Accept: application/json

###
POST {{host}}/users
Content-Type: application/json

{
    "name": "test"
}

###
PUT {{host}}/users/1
Content-Type: application/json

{
    "name": "test emoji 👽💔"
}

###
DELETE {{host}}/users/2
