
@host = http://localhost:8000

###
HEAD {{host}}/users
Accept: application/json

###
GET {{host}}/users
Accept: application/json

###
GET {{host}}/users/1
Accept: application/json

###
POST {{host}}/users
Content-Type: application/json

{
    "username": "junlapong",
    "email": "user@mail.com",
    "firstname": "Jun",
    "lastname": "Lee"
}

###
PUT {{host}}/users/1
Content-Type: application/json

{
    "firstname": "Jun 🇹🇭",
    "updated_date": "2020-04-28T07:45:59Z"
}

###
DELETE {{host}}/users/2
